version: "3.9"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - type: bind
      source: ./frontend
      target: /usr/src/frontend
    #"react-app"の部分がプロジェクト名になる
    command: sh -c "cd react-app && yarn start" 
    ports:
      - 3000:3000
    stdin_open: true #標準入力をコンテナと紐付ける
